# Przekierowanie subdomeny kampinos.aktmamut.eu na gotową mapę
[[redirects]]
  from = "https://kampinos.aktmamut.eu/*"
  to = "/maps/kampinos.html"
  status = 200
  force = true

# Kompresja GeoJSON
[[headers]]
  for = "/pages/expeditions/expeditions.geojson"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/json"
